/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.GestionCliente;
import Controlador.GestionVehiculos;
import Modelo.Vehiculo;
import javax.swing.JOptionPane;

/**
 * Clase jPanel la cual gestiona todas las acciones relacionadas a los vehiculos.
 * @author Henry
 */
public class AnadirVehiculo extends javax.swing.JPanel {
    StringBuilder servicioBuilder = new StringBuilder();
    GestionVehiculos conexionVehiculo = new GestionVehiculos();
    GestionCliente conexionCliente = new GestionCliente();
    Vehiculo vehiculo = new Vehiculo();
    String golpes;
    /**
     * Creates new form AnadirVehiculo
     */
    public AnadirVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        registeredIdVehiculo = new javax.swing.JTextField();
        jB_EliminarVehiculo = new javax.swing.JButton();
        jB_consultarVehiculos = new javax.swing.JButton();
        jB_ConsultarClientes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCb_Marchamo = new javax.swing.JCheckBox();
        jCb_Rtv = new javax.swing.JCheckBox();
        jCb_Golpes = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        registeredNotas = new javax.swing.JTextField();
        jB_agregarVehiculo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        registeredClienteId = new javax.swing.JTextField();
        registeredModelo = new javax.swing.JTextField();
        registeredPlaca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jCb_cambioAceite = new javax.swing.JCheckBox();
        jCb_CambioFibras = new javax.swing.JCheckBox();
        jCb_halogenos = new javax.swing.JCheckBox();

        setPreferredSize(new java.awt.Dimension(730, 440));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(370, 276));

        jLabel4.setText("Eliminar Vehiculo");

        jLabel5.setText("ID Vehiculo");

        jB_EliminarVehiculo.setText("Eliminar");
        jB_EliminarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_EliminarVehiculoActionPerformed(evt);
            }
        });

        jB_consultarVehiculos.setText("Consultar Vehiculos");
        jB_consultarVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_consultarVehiculosActionPerformed(evt);
            }
        });

        jB_ConsultarClientes.setText("Consultar Clientes");
        jB_ConsultarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ConsultarClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(31, 31, 31)
                                .addComponent(registeredIdVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(53, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jB_consultarVehiculos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jB_ConsultarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jB_EliminarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_consultarVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_ConsultarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(registeredIdVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(jB_EliminarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jLabel1.setText("Modelo");

        jLabel2.setText("Placa");

        jCb_Marchamo.setText("Marchamo");
        jCb_Marchamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCb_MarchamoActionPerformed(evt);
            }
        });

        jCb_Rtv.setText("RTV");

        jCb_Golpes.setText("Golpes");

        jLabel3.setText("Notas");

        registeredNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registeredNotasActionPerformed(evt);
            }
        });

        jB_agregarVehiculo.setText("Agregar Vehiculo");
        jB_agregarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_agregarVehiculoActionPerformed(evt);
            }
        });

        jLabel6.setText("ClienteID");

        registeredPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registeredPlacaActionPerformed(evt);
            }
        });

        jLabel7.setText("Servicios");

        jCb_cambioAceite.setText("Cambio Aceite");

        jCb_CambioFibras.setText("Cambio Fibras");

        jCb_halogenos.setText("Halogenos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jB_agregarVehiculo)
                        .addGap(112, 112, 112))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCb_Marchamo)
                                    .addComponent(jCb_Rtv)
                                    .addComponent(jCb_Golpes)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(27, 27, 27)
                                        .addComponent(registeredNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jLabel2))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(registeredClienteId)
                                            .addComponent(registeredModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                            .addComponent(registeredPlaca)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCb_cambioAceite)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCb_CambioFibras)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCb_halogenos))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(registeredClienteId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(registeredModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(registeredPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCb_Marchamo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCb_Rtv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCb_Golpes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registeredNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCb_cambioAceite)
                    .addComponent(jCb_CambioFibras)
                    .addComponent(jCb_halogenos))
                .addGap(34, 34, 34)
                .addComponent(jB_agregarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    
   
    private void jCb_MarchamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCb_MarchamoActionPerformed
        // TODO add your handling code here:    
    }//GEN-LAST:event_jCb_MarchamoActionPerformed

    /**
     * Boton para eliminar vehiculo de la base de datos por medio del ID
     * @param evt 
     */
    private void jB_EliminarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_EliminarVehiculoActionPerformed
        // TODO add your handling code here:
        try{
            if(registeredIdVehiculo.getText().isEmpty()){
                JOptionPane.showMessageDialog(this,"Por favor ingrese ID del Vehiculo.");
            }else{
                int id = Integer.valueOf(registeredIdVehiculo.getText());
                conexionVehiculo.eliminarVehiculo(id);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al eliminar el vehículo.", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jB_EliminarVehiculoActionPerformed
    
    private void registeredNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registeredNotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registeredNotasActionPerformed
    /**
     * Boton para agregar vehiculo a la base de datos
     * @param evt 
     */
    private void jB_agregarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_agregarVehiculoActionPerformed
        // TODO add your handling code here:
        try{
            if(registeredClienteId.getText().isEmpty() || registeredModelo.getText().isEmpty() || registeredPlaca.getText().isEmpty()){
                JOptionPane.showMessageDialog(this,"Por favor ingrese los datos del Vehiculo.");  
            }else{
                if(jCb_Marchamo.isSelected() && jCb_Rtv.isSelected()){
                    vehiculo.setMarchamo("Si");
                    vehiculo.setRtv("Si");
                    vehiculo.setClienteId(this.registeredClienteId.getText());
                    vehiculo.setModelo(this.registeredModelo.getText());
                    vehiculo.setPlaca(this.registeredPlaca.getText()); 
                    if(jCb_Golpes.isSelected()){
                        golpes = "Si";
                        vehiculo.setNotas(this.registeredNotas.getText());
                    }else{
                        golpes = "No";
                        vehiculo.setNotas("No presenta Golpes");
                    }
                    //Logica de los checbox de los servicios
                    if (jCb_cambioAceite.isSelected()) {
                        servicioBuilder.append("Aceite");
                    }
                    if (jCb_CambioFibras.isSelected()) {
                        if (servicioBuilder.length() > 0) {
                            servicioBuilder.append(" ");
                        }
                        servicioBuilder.append("Fibras");
                    }
                    if (jCb_halogenos.isSelected()) {
                        if (servicioBuilder.length() > 0) {
                            servicioBuilder.append(" ");
                        }
                        servicioBuilder.append("Halogenos");
                    }

                    vehiculo.setServicio(servicioBuilder.length() > 0 ? servicioBuilder.toString() : "No se realizaron servicios");

                    //Ingreso de vehiculo a la base de datos
                    conexionVehiculo.insertarVehiculo(vehiculo);

                    //System.out.print("funciono");
                }else{
                    JOptionPane.showMessageDialog(null,"No se Aceptan Vehiculos sin Marchamo o Rtv al Dia");            
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al agregar el vehículo.", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jB_agregarVehiculoActionPerformed
    
    private void registeredPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registeredPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registeredPlacaActionPerformed
    /**
     * Bonton para consultar los vehiculos que se encuentran en la base de datos
     * @param evt 
     */
    private void jB_consultarVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_consultarVehiculosActionPerformed
        // TODO add your handling code here:
        try{
            conexionVehiculo.consultarVehiculo();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al consultar los vehiculos.", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jB_consultarVehiculosActionPerformed
    /**
     * Boton para consultar los clientes que se encuentran en la base de deatos.
     * @param evt 
     */
    private void jB_ConsultarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ConsultarClientesActionPerformed
        // TODO add your handling code here:
        try{
            conexionCliente.consultarCliente();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al consultar los clientes.", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jB_ConsultarClientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_ConsultarClientes;
    private javax.swing.JButton jB_EliminarVehiculo;
    private javax.swing.JButton jB_agregarVehiculo;
    private javax.swing.JButton jB_consultarVehiculos;
    private javax.swing.JCheckBox jCb_CambioFibras;
    private javax.swing.JCheckBox jCb_Golpes;
    private javax.swing.JCheckBox jCb_Marchamo;
    private javax.swing.JCheckBox jCb_Rtv;
    private javax.swing.JCheckBox jCb_cambioAceite;
    private javax.swing.JCheckBox jCb_halogenos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField registeredClienteId;
    private javax.swing.JTextField registeredIdVehiculo;
    private javax.swing.JTextField registeredModelo;
    private javax.swing.JTextField registeredNotas;
    private javax.swing.JTextField registeredPlaca;
    // End of variables declaration//GEN-END:variables
}
