/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.GestionCliente;
import Controlador.GestionHistorico;
import Modelo.Vehiculo;
import Modelo.Cliente;
import Controlador.GestionVehiculos;
import Modelo.Historico;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 * Clase jPanel la cual muestra y gestiona las Facturas
 * @author Henry
 */
public class Facturacion extends javax.swing.JPanel {
    GestionVehiculos conexionVehiculo = new GestionVehiculos();
    GestionCliente conexionCliente = new GestionCliente();
    GestionHistorico conexionHistorico = new GestionHistorico();
    Vehiculo vehiculo = new Vehiculo();
    Cliente cliente = new Cliente();
    Historico factura = new Historico();
    int idVehiculo;
    int clienteId;
    
    /**
     * Creates new form Facturacion
     */
    public Facturacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_Date = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_nombreFactura = new javax.swing.JLabel();
        jLabel_servicios = new javax.swing.JLabel();
        jLabel_precio = new javax.swing.JLabel();
        jLabel_placaVehiculo = new javax.swing.JLabel();
        jB_generarFactura = new javax.swing.JButton();
        jB_imprimirFactura = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        registeredIdVehiculo = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(730, 440));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Placa Vehiculo:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Precio:");

        jLabel4.setText("Servicios:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_servicios, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_nombreFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_placaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_nombreFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_placaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_servicios, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jB_generarFactura.setText("Generar Factura");
        jB_generarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_generarFacturaActionPerformed(evt);
            }
        });

        jB_imprimirFactura.setText("Imprimir Factura");
        jB_imprimirFactura.setPreferredSize(new java.awt.Dimension(117, 27));
        jB_imprimirFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_imprimirFacturaActionPerformed(evt);
            }
        });

        jLabel5.setText("ID Vehiculo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registeredIdVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jB_imprimirFactura, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(jB_generarFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(registeredIdVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jB_generarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jB_imprimirFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Metodo el para definir fecha actual y mostrarla en texto.
     */
    private void setDate(){
        try{
            LocalDate now = LocalDate.now();
            int year = now.getYear();
            int dia = now.getDayOfMonth();
            int month = now.getMonthValue();
            String[] meses = {"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto"
                ,"Septiembre","Octubre","Noviembre","Diciembre"};
            jLabel_Date.setText(dia+"/"+month+"/"+year);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al establecer la fecha.", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    /**
     * Metodo para definir el precio del servicio, recibe un servico como String el cual por medio de 
     * switch va por todos los posibles escenarios para asi definir y retornar un precio.
     * @param servicio
     * @return 
     */
    public static String definirPrecio(String servicio) {
        String precio;

        switch (servicio) {
            case "Aceite":
                precio = "10 USD";
                break;
            case "Fibras":
                precio = "15 USD";
                break;
            case "Halogenos":
                precio = "20 USD";
                break;
            case "Aceite Fibras Halogenos":
                precio = "40 USD";  
                break;
            case "Aceite Fibras":
                precio = "25 USD";  
                break;
            case "Aceite Halogenos":
                precio = "28 USD";  
                break;
            case "Fibras Halogenos":
                precio = "32 USD"; 
                break;
            case "No se realizaron servicios":
                precio = "0 USD";
                break;
            default:
                precio = "Servicio no reconocido";
        }

        return precio;
    }
    /**
     * Boton para generar las facturas, extrae la informacion segun el idVehiculo que se encuentre 
     * en el respectivo textField, una vez encontrado el vehiculo en la base de datos crea un objeto de tipo vehiculo y uno de
     * tipo cliente para asi poder extraer la informacion y mostrarla en texto
     * @param evt 
     */
    private void jB_generarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_generarFacturaActionPerformed
        // TODO add your handling code here:
        try{
            if(registeredIdVehiculo.getText().isEmpty()){
                JOptionPane.showMessageDialog(this,"Por favor ingrese ID del Vehiculo");
            }else{            
                idVehiculo = Integer.valueOf(this.registeredIdVehiculo.getText());
                //Creando Objeto Vehiculo
                vehiculo = conexionVehiculo.optenerDatosVehiculoPorID(idVehiculo);

                if(vehiculo != null){
                    factura.setPlacaVehiculo(vehiculo.getPlaca());
                    factura.setServicio(vehiculo.getServicio());

                    clienteId = Integer.valueOf(vehiculo.getClienteId());

                    jLabel_placaVehiculo.setText(vehiculo.getPlaca());
                    jLabel_servicios.setText(vehiculo.getServicio());
                    setDate();

                    factura.setPrecio(definirPrecio(vehiculo.getServicio()));
                    jLabel_precio.setText(factura.getPrecio());

                    //Creando Objeto Cliente
                    cliente = conexionCliente.optenerDatosClientePorID(clienteId);
                    if(cliente != null){
                        factura.setNombreCliente(cliente.getNombre());
                        jLabel_nombreFactura.setText(factura.getNombreCliente());
                    }else{
                        System.out.println("Cliente no encontrado.");
                    }
                JOptionPane.showMessageDialog(this, "Factura generada!");
                }else{
                    System.out.print("Vehículo no encontrado.");
                }
            }
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Error al generar la factura.", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jB_generarFacturaActionPerformed
    /**
     * Boton para imprimir factura previamente generada por medio del boton de generar factura.
     * La informacion de la factura se guarda en una base de datos de historicos y se borra el 
     * vehiculo gestionado de la base de datos de vehiculos segun el idVehiculo.
     * @param evt 
     */
    private void jB_imprimirFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_imprimirFacturaActionPerformed
        try{  
            conexionHistorico.insertarFactura(factura);
            conexionVehiculo.eliminarVehiculo(idVehiculo);
            JOptionPane.showMessageDialog(this,"Factura guardada en Historico y Cliente Notificado");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error al imprimir la factura.", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jB_imprimirFacturaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_generarFactura;
    private javax.swing.JButton jB_imprimirFactura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_Date;
    private javax.swing.JLabel jLabel_nombreFactura;
    private javax.swing.JLabel jLabel_placaVehiculo;
    private javax.swing.JLabel jLabel_precio;
    private javax.swing.JLabel jLabel_servicios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField registeredIdVehiculo;
    // End of variables declaration//GEN-END:variables
}
