/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Historico;
import Controlador.GestionHistorico;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 * Clase jPanel la cual muestra y gestiona la tabla de datos que refleja la base de datos de historico
 * @author Henry
 */
public class TablaHistorico extends javax.swing.JPanel {
    GestionHistorico conexionHistoricos = new GestionHistorico();
    /**
     * Creates new form TablaHistorico
     */
    public TablaHistorico() {
        initComponents();
        
        //Generando las columnas necesarias para la tabla
        String[] columnas = {"ID Factura", "Fecha", "Nombre Cliente", "Placa Vehículo", "Servicio", "Precio"};
        DefaultTableModel tableModel = new DefaultTableModel(columnas, 0);
        jTable_historicos.setModel(tableModel);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_historicos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(730, 440));

        jTable_historicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable_historicos);

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Boton el cual carga los datos de la base de datos historico para reflejarlos 
     * en la tabla
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cargarDatos();   
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * Metodo para cargar los datos de la base historico, crear un objeto Historico
     * para asi poder utilizar la informacion del objeto para rellenar la tabla.
     */
    private void cargarDatos() {
        List<Historico> historicos = conexionHistoricos.obtenerTablaHistoricos();
        DefaultTableModel tableModel = (DefaultTableModel) jTable_historicos.getModel();
        tableModel.setRowCount(0);
        
        for (Historico h : historicos) {
            tableModel.addRow(new Object[]{
                h.getIdFactura(),
                h.getFecha(),
                h.getNombreCliente(),
                h.getPlacaVehiculo(),
                h.getServicio(),
                h.getPrecio()
            });
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_historicos;
    // End of variables declaration//GEN-END:variables
}
